### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    id: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    summary: >-
      Describes a Chaos event that gets generated when an unexpected event
      occurs

      in the Chaos engine.

      For example, due to the cluster snapshot being inconsistent, while
      faulting

      a faultable entity, Chaos found that the entity was alreay faulted --
      which

      would be an unexpected event.
    fullName: azure-servicefabric.TestErrorChaosEvent
    type: Class
    children:
      - 'azure-servicefabric.TestErrorChaosEvent.#ctor'
      - 'azure-servicefabric.TestErrorChaosEvent#mapper'
    langs:
      - js
  - id: 'azure-servicefabric.TestErrorChaosEvent.#ctor'
    uid: 'azure-servicefabric.TestErrorChaosEvent.#ctor'
    parent: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent()
    fullName: azure-servicefabric.TestErrorChaosEvent.TestErrorChaosEvent()
    summary: ''
    type: Constructor
    syntax:
      content: new TestErrorChaosEvent()
    langs:
      - js
  - uid: 'azure-servicefabric.TestErrorChaosEvent#mapper'
    id: 'azure-servicefabric.TestErrorChaosEvent#mapper'
    parent: azure-servicefabric.TestErrorChaosEvent
    name: mapper()
    summary: Defines the metadata of TestErrorChaosEvent
    fullName: azure-servicefabric.TestErrorChaosEvent.mapper()
    type: Function
    syntax:
      return:
        type:
          - object
        description: metadata of TestErrorChaosEvent
      content: function mapper()
    langs:
      - js
